# Generated by Django 3.1.1 on 2020-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Профессия')),
                ('category', models.CharField(max_length=32, verbose_name='Категория')),
                ('company', models.CharField(max_length=32, verbose_name='Компания')),
                ('salary_from', models.IntegerField(verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(verbose_name='Зарплата от')),
                ('posted', models.DateField(auto_now_add=True, verbose_name='Дата размещения')),
                ('desc', models.CharField(max_length=32, verbose_name='ХЗ')),
            ],
        ),
    ]
